--- #YAML:1.0
name:                Win32-GUI-HyperLink
version:             0.14
abstract:            A Win32::GUI Hyperlink control
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Test::More:                    0
    Win32::API:                    0
    Win32::GUI:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Robert May <robertmay@cpan.org>
